### ISSUE TITLE
Finalne poprawki projektu

### ISSUE THREAD

**Issue by Jvsin** [JakubTuta/Strona-randkowa#79]
- [x]  usunąć panel społeczności z navbarów
- [ ]  zmienić nazwę aplikacji
- [ ]  kolorami primary/secondary itp
- [ ]  wszystkie data pickery dodać żeby dostosowywał się do koloru motywu a nie był cały czas czarny
- [ ]  sprawdzić czy użytkownik ma możliwość zmiany języka w profilu
- [ ] przyciski powrotu do poprzedniej aktywności (wyjść z utwórz wydarzenia)
- [ ] jak jesteśmy zalogowani i zmieniamy język zapisać to w obiekcie usera
- [ ] po naciśnięciu karty ze znajomymi w głównym menu przenosi nas odrazu do chatu z tą osobą lub wyświetla nam jej profil za pomocą profileDrawer [opcjonalnie]
- [x] język francuski @Lecrut
- [ ] gdy nie ma nadchodzących wydarzeń, wyświetlić carda w stylu "Brak nadchodzących wydarzen" (czyli gdy futureEvents.len == 0)
- [ ] zasady walidacji imienia - 3 literowe np. Ali i długie nazwiska

**Comment by Jvsin** [comment]
- [ ] usunąć panel społeczności z navbarów
- [ ] zmienić nazwę aplikacji
- [ ] kolorami primary/secondary itp

**Comment by Lecrut** [comment]
- [ ] wszystkie data pickery dodać żeby dostosowywał się do koloru motywu a nie był cały czas czarny

**Comment by Lecrut** [comment]
- [ ] sprawdzić czy użytkownik ma możliwość zmiany języka w profilu 

aktualnie loguje się i zmienia mi się na ten język co jest w modelu usera ale czy mogę go zmienić

**Comment by Lecrut** [comment]
- [ ] przyciski powrotu do poprzedniej aktywności (wyjść z utwórz wydarzenia)

**Comment by Lecrut** [comment]
- [ ] jak jesteśmy zalogowani i zmieniamy język zapisać to w obiekcie usera

**Comment by Jvsin** [comment]
OPCJONALNIE: 
- [ ] po naciśnięciu karty ze znajomymi w głównym menu przenosi nas odrazu do chatu z tą osobą lub wyświetla nam jej profil za pomocą profileDrawer

**Comment by Jvsin** [comment]
- [ ] język francuski @Lecrut
